### ISSUE TITLE
vagrant deploy is broken

### ISSUE THREAD

**Issue by binary1230** [magfest/simple-rams-deploy#27]
doing a new deploy for the first time in a while, saw this go by while doing a new magstock apply:

```
[vagrant-ubuntu-trusty-64] out: Error: /usr/bin/easy_install supervisor==3.0 returned 1 instead of one of [0]
[vagrant-ubuntu-trusty-64] out: Error: /Stage[main]/Supervisor/Exec[easy_install-supervisor]/returns: change from notrun to 0 failed: /usr/bin/easy_install supervisor==3.0 returned 1 instead of one of [0]
[vagrant-ubuntu-trusty-64] out: Notice: /Stage[main]/Supervisor/Exec[easy_install-superlance]: Dependency Exec[easy_install-supervisor] has failures: true
[vagrant-ubuntu-trusty-64] out: Warning: /Stage[main]/Supervisor/Exec[easy_install-superlance]: Skipping because of failed dependencies
[vagrant-ubuntu-trusty-64] out: Notice: /Stage[main]/Supervisor/File[/var/log/supervisor]: Dependency Exec[easy_install-supervisor] has failures: true
[vagrant-ubuntu-trusty-64] out: Warning: /Stage[main]/Supervisor/File[/var/log/supervisor]: Skipping because of failed dependencies
[vagrant-ubuntu-trusty-64] out: Notice: /Stage[main]/Supervisor/File[/etc/supervisord.conf]: Dependency Exec[easy_install-supervisor] has failures: true
[vagrant-ubuntu-trusty-64] out: Warning: /Stage[main]/Supervisor/File[/etc/supervisord.conf]: Skipping because of failed dependencies
[vagrant-ubuntu-trusty-64] out: Notice: /Stage[main]/Supervisor/Service[supervisord]: Dependency Exec[easy_install-supervisor] has failures: true
[vagrant-ubuntu-trusty-64] out: Warning: /Stage[main]/Supervisor/Service[supervisord]: Skipping because of failed dependencies [vagrant-ubuntu-trusty-64] out: Notice: ```

I'm setting up shop at magstock and will probably check on this since I need a deploy environment : )

**Comment by binary1230** [comment]
disclaimer: my internet is also weird so it could be transient stuff : )

**Comment by binary1230** [comment]
also saw this go by:

```
[vagrant-ubuntu-trusty-64] run: /home/vagrant/uber/sideboard/env/bin/sep alembic heads
[vagrant-ubuntu-trusty-64] out: fc4b8eb3a35f (uber) (head)
[vagrant-ubuntu-trusty-64] out: fc791d73e762 (uber, panels, bands) (head)
[vagrant-ubuntu-trusty-64] out: bb334f039eac (magstock, uber) (head)
[vagrant-ubuntu-trusty-64] out:

[vagrant-ubuntu-trusty-64] sudo: supervisorctl stop all
[vagrant-ubuntu-trusty-64] out: Traceback (most recent call last):
[vagrant-ubuntu-trusty-64] out:   File "/usr/local/bin/supervisorctl", line 5, in <module>
[vagrant-ubuntu-trusty-64] out:     from pkg_resources import load_entry_point
[vagrant-ubuntu-trusty-64] out:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
[vagrant-ubuntu-trusty-64] out:     working_set = WorkingSet._build_master()
[vagrant-ubuntu-trusty-64] out:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
[vagrant-ubuntu-trusty-64] out:     ws.require(__requires__)
[vagrant-ubuntu-trusty-64] out:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
[vagrant-ubuntu-trusty-64] out:     needed = self.resolve(parse_requirements(requirements))
[vagrant-ubuntu-trusty-64] out:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
[vagrant-ubuntu-trusty-64] out:     raise DistributionNotFound(req)
[vagrant-ubuntu-trusty-64] out: pkg_resources.DistributionNotFound: meld3>=0.6.5
[vagrant-ubuntu-trusty-64] out:


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: supervisorctl stop all
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "supervisorctl stop all"
```

**Comment by binary1230** [comment]
investigating, it looks like we're installing supervisor through easy_install or something.... weird. will investigate

**Comment by binary1230** [comment]
VAGRANT ONLY, sorry didn't mean to give anyone a heart attack, production seems fine

**Comment by binary1230** [comment]
I think this was fixed already, so closing.  will re-open if another one i'm looking at right now breaks.
